version: 0.9.{build}.0

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: {version}
  assembly_file_version: {version}
  assembly_informational_version: {version}

configuration: Release

build:
  verbosity: minimal

after_test:
  - ps: .\.nuget\pack.ps1

deploy:
  provider: NuGet
  api_key:
    secure: TC5YxUxSq+xio84ZpfmKKSZR3BerpkvquwX2Hzqd2Xz6ZQTDu2hlWqH95jLZWJkP
  artifact: /.*\.nupkg/
